#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: fbduddn97@gmail.com
#    password: "*#ryu444081"
#    properties:
#    mail.smtp,auth: true
#    mail.smtp.starttls.enable: true

# db source
#spring:
#  datasource:
#      url: jdbc:mysql://gogodb.cplrxb3kh41a.ap-northeast-2.rds.amazonaws.com:3306/gogodb
#      username: gogoboy
#      password: gogo1234
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 12345678901234567890123456789012
