#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: fbduddn97@gmail.com
#    password: "*#ryu444081"
#    properties:
#    mail.smtp,auth: true
#    mail.smtp.starttls.enable: true



jwt:
  secret: 12345678901234567890123456789012
